FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu20.04
# 타임존 설정
RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
# 필요한 패키지 설치 
RUN apt-get update && apt-get install -y locales git wget net-tools vim openssh-server awscli
# 한글 설정
RUN localedef -f UTF-8 -i ko_KR ko_KR.UTF-8
RUN \    
    apt-get update && \
    apt-get install -y nano curl wget gcc build-essential sudo

WORKDIR /home/leap
COPY ./tuning ./tuning
COPY ./docker/tuning/requirements.txt .
# yank 된 pyairports==2.1.1 을 로컬 wheel 로 제공
COPY ./docker/tuning/vendor ./vendor

# Install miniconda3
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 
RUN conda --version
RUN conda env list
RUN /bin/bash -c "conda init"
# 최신 miniconda default 채널 Terms of Service 동의 (구버전 이미지 빌드 당시엔 없던 최근 Anaconda 정책 변경)
RUN /bin/bash -c "conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r"
RUN /bin/bash -c "conda create -n vllm python=3.10 -y"
# flash-attn 은 소스 컴파일(60분+/OOM) 대신 GitHub prebuilt wheel(torch2.4/cu12/py310/cxx11abiFALSE) 사용.
# yank 된 pyairports 는 --find-links(로컬 vendor)로 제공.
RUN /bin/bash -c "source activate vllm && pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu121 && pip install https://github.com/Dao-AILab/flash-attention/releases/download/v2.6.3/flash_attn-2.6.3+cu123torch2.4cxx11abiFALSE-cp310-cp310-linux_x86_64.whl && pip install --find-links /home/leap/vendor -r requirements.txt"


ENV HOST=10.10.20.66
ENV BACKEND_PORT=11188
ENV EVAL_PORT=11189
ENV TUNING_PORT=11190
ENV FRONTEND_PORT=11191
EXPOSE 11190
    
#ENTRYPOINT ["/bin/bash", "-c", "source activate vllm && exec \"$@\"", "--"]